site_name: jhrwiki
use_directory_urls: false

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: logo
  favicon: img/img.jpg

nav:
  - 首页: index.md

  - 日常工具:
      - git: develop/git.md
      - vscode: develop/vscode.md
      - 利用MkDocs搭建博客: develop/blog.md
      - Linux游戏体验: develop/steam.md

  - 语言:
      - C++: engineering/cpp.md
      - Makefile: engineering/makefile.md
      - Python: engineering/py.md
      - Golang: engineering/go.md
